name: Bug/Crash report.
description: Create a bug report to help us improve our plugin.
labels:
  - "Bug"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report correctly.

  - type: textarea
    id: what
    attributes:
      label: What is the bug or the crash?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the issue
      description: |
        Kindly provide the step-by-step instructions to reproduce the issue.
        You can also include sample datasets and the QGIS project file to help us understand and replicate the behavior.
        Feel free to add screencasts or screenshots; simply drag and drop them into the text box.

        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: about-info
    attributes:
      label: QGIS Versions
      description: |
        In QGIS, go to the Help menu -> About, click in the table, press Ctrl+A, then Ctrl+C, and finally, paste the information here.
        Avoid using screenshots for this purpose.
    validations:
      required: true

  - type: textarea
    id: os-type
    attributes:
      label: Operating System
      description: |
        Please specify the operating system you are using.
